'use client'

import { useEffect, useRef } from 'react'
import { useCaptionsOptions } from './videojs'
import { useAutoCaptionsProgress } from './AutoCaptionsProgressContext'

const POLL_INTERVAL_MS = 3000
const POLL_TIMEOUT_MS = 15 * 60 * 1000

/**
 * JIT auto-caption generation manager (port of the vidstack AutoCaptionTracks
 * per docs/auto-captions-client-architecture.md).
 *
 * The <track> elements themselves are rendered by PlayerMedia from React
 * state; this component only watches the captions-menu selection, triggers
 * generation, polls the job, and asks the parent (via onNonce) to cache-bust
 * the track src when the VTT finally exists. Because React updates the same
 * <track> element's src attribute in place, the underlying TextTrack (and its
 * 'showing' mode) survives the refetch — vidstack's recreate-workaround dance
 * is no longer needed, but a guarded re-assert stays as a belt-and-braces
 * measure for engines that reset the mode on src change.
 */
export default function AutoCaptionsManager({ captions, onNonce }) {
  const captionsOptions = useCaptionsOptions()
  const { update: updateProgress, clear: clearProgress } = useAutoCaptionsProgress()

  // In-flight: label is currently between trigger fetch and pollJob settling.
  // Processed: label has been processed once this video session — guards
  // against re-trigger when the user toggles the track off and back on.
  const inFlight = useRef(new Set())
  const processedLabels = useRef(new Set())
  // Last label the user selected — used to re-assert selection if the
  // src-refresh knocks the track back to disabled.
  const desiredLabelRef = useRef(null)

  const selectedValue = captionsOptions?.value
  const selectedOption = captionsOptions?.options?.find((o) => o.value === selectedValue)
  const selectedLabel =
    selectedOption && selectedOption.value !== 'off' ? String(selectedOption.label) : null

  const callbacksRef = useRef({})
  callbacksRef.current = { updateProgress, clearProgress, onNonce, captions }

  // Trigger generation when an auto-generated track is selected.
  useEffect(() => {
    if (!selectedLabel) return
    desiredLabelRef.current = selectedLabel
    const entry = captions?.[selectedLabel]
    // Gate on autoGenerated only. The pending flag has been an unreliable
    // signal — the sync layer doesn't always preserve it. The trigger route
    // is idempotent (200 if file exists, 202 if generation needed).
    if (!entry?.autoGenerated) return
    if (inFlight.current.has(selectedLabel)) return
    if (processedLabels.current.has(selectedLabel)) return
    console.log('[AutoCaptionsManager] track selected:', selectedLabel, {
      autoGenerated: entry.autoGenerated,
      pending: entry.pending,
    })
    handleTrackSelected(selectedLabel, entry)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedLabel, captions])

  // Belt-and-braces re-assert: if the selection snapped to Off while the
  // user's chosen (already processed) track is still available — e.g. the
  // engine reset the track mode when its src changed — re-select it.
  useEffect(() => {
    if (!captionsOptions) return
    const desired = desiredLabelRef.current
    if (!desired || !processedLabels.current.has(desired)) return
    if (captionsOptions.value !== 'off') return
    const option = captionsOptions.options.find((o) => String(o.label) === desired)
    if (option) {
      console.log('[AutoCaptionsManager] re-asserting selection for', desired)
      captionsOptions.setValue(option.value)
    }
  }, [captionsOptions])

  async function handleTrackSelected(label, entry) {
    inFlight.current.add(label)
    const { updateProgress: update, clearProgress: clear, onNonce: bumpNonce } = callbacksRef.current

    // Surface "Generating…" on the row immediately so the user gets visual
    // confirmation on click — before the trigger fetch round-trips. For
    // already-ready tracks (200 path) the finally block clears it ~1 s later;
    // brief flicker is acceptable.
    update(label, { status: 'running', progressPct: null })

    try {
      const triggerRes = await fetch(entry.url)
      console.log('[AutoCaptionsManager] trigger response:', label, triggerRes.status)

      if (triggerRes.status === 200) {
        // File exists — the browser's automatic track-load fetch also got 200
        // VTT, so cues are already populating. Mark processed; no nonce bump
        // needed since the existing src returned the right bytes.
        processedLabels.current.add(label)
        return
      }

      if (triggerRes.status !== 202) {
        // 401/429/503/etc. — silently dropped. Track stays as-is, user can retry.
        console.warn(`Auto-caption trigger returned HTTP ${triggerRes.status}`)
        return
      }

      const triggerBody = await safeJson(triggerRes)
      const jobId = triggerBody?.jobId
      if (!jobId) {
        console.warn('Auto-caption trigger accepted but no jobId returned')
        return
      }

      // Enrich the running state with the jobId now that we have it.
      update(label, { status: 'running', jobId, progressPct: null })
      console.log('[AutoCaptionsManager] polling job:', jobId, 'for', label)

      const result = await pollJob(jobId, entry.sourceServerId, (data) => {
        update(label, {
          status: data.status,
          progressPct: typeof data.progressPct === 'number' ? data.progressPct : null,
        })
      })

      if (result.status === 'succeeded') {
        // Mark processed BEFORE bumping the nonce so any selection churn from
        // the src refresh short-circuits in the trigger gate.
        processedLabels.current.add(label)
        // Bump the nonce → PlayerMedia updates the <track> src → the browser
        // refetches the URL → now returns 200 VTT → cues populate.
        bumpNonce(label, String(Date.now()))
      } else {
        console.warn(`Auto-caption job failed: ${result.error || 'unknown error'}`)
      }
    } catch (err) {
      console.warn(`Auto-caption trigger error: ${err.message}`)
    } finally {
      inFlight.current.delete(label)
      // Drop the "Generating…" suffix on every code path — success leaves the
      // track loaded with cues; failures revert to the plain label.
      clear(label)
    }
  }

  async function pollJob(jobId, serverId, onProgress) {
    const start = Date.now()
    const url = `/api/authenticated/captions/jobs/${encodeURIComponent(jobId)}${
      serverId ? `?serverId=${encodeURIComponent(serverId)}` : ''
    }`
    while (Date.now() - start < POLL_TIMEOUT_MS) {
      await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS))
      try {
        const res = await fetch(url)
        if (!res.ok) continue
        const data = await res.json()
        if (typeof onProgress === 'function') onProgress(data)
        if (data.status === 'succeeded' || data.status === 'failed') {
          return data
        }
      } catch (_) {
        // transient — keep polling
      }
    }
    return { status: 'failed', error: 'Polling timeout' }
  }

  return null
}

async function safeJson(res) {
  try {
    return await res.json()
  } catch {
    return null
  }
}
