'use client'

import { Track, useMediaPlayer } from '@vidstack/react'
import { useEffect, useRef, useState } from 'react'
import { toast } from 'react-toastify'

const POLL_INTERVAL_MS = 3000
const POLL_TIMEOUT_MS = 15 * 60 * 1000

export default function AutoCaptionTracks({ captions }) {
  const player = useMediaPlayer()
  const [nonces, setNonces] = useState({})
  const inFlight = useRef(new Set())
  const showAfterUpdate = useRef(new Set())

  useEffect(() => {
    if (!player?.textTracks) return
    const tt = player.textTracks

    function onChange() {
      const tracks = Array.from(tt)
      for (const track of tracks) {
        if (track.mode !== 'showing') continue
        const entry = captions?.[track.label]
        if (!entry?.autoGenerated || !entry?.pending) continue
        if (inFlight.current.has(track.label)) continue
        handleTrackSelected(track, entry)
      }
    }

    tt.addEventListener('change', onChange)
    return () => tt.removeEventListener('change', onChange)
  }, [player, captions])

  useEffect(() => {
    if (!player?.textTracks || showAfterUpdate.current.size === 0) return
    const tracks = Array.from(player.textTracks)
    for (const label of Array.from(showAfterUpdate.current)) {
      const t = tracks.find((x) => x.label === label)
      if (t) {
        t.mode = 'showing'
        showAfterUpdate.current.delete(label)
      }
    }
  })

  async function handleTrackSelected(track, entry) {
    const label = track.label
    inFlight.current.add(label)
    track.mode = 'disabled'

    let toastId
    try {
      const triggerRes = await fetch(entry.url)

      if (triggerRes.status === 200) {
        markReady(label)
        return
      }

      if (triggerRes.status === 429) {
        const data = await safeJson(triggerRes)
        toast.error(
          `Caption generation rate limit reached${
            data?.retryAfterSec ? `. Try again in ${Math.ceil(data.retryAfterSec / 60)} min.` : '.'
          }`
        )
        return
      }

      if (triggerRes.status === 401) {
        toast.error('Sign in to generate captions.')
        return
      }

      if (triggerRes.status !== 202) {
        toast.error(`Captions unavailable (HTTP ${triggerRes.status})`)
        return
      }

      const triggerBody = await safeJson(triggerRes)
      const jobId = triggerBody?.jobId
      if (!jobId) {
        toast.error('Caption generation accepted but no jobId returned')
        return
      }

      toastId = toast.info(
        `Generating ${entry.srcLang.toUpperCase()} captions — this may take a few minutes.`,
        { autoClose: 8000 }
      )

      const result = await pollJob(jobId, entry.sourceServerId)

      if (result.status === 'succeeded') {
        toast.success(`${entry.srcLang.toUpperCase()} captions ready`)
        markReady(label)
      } else {
        toast.error(`Caption generation failed: ${result.error || 'unknown error'}`)
      }
    } catch (err) {
      toast.error(`Caption generation error: ${err.message}`)
    } finally {
      if (toastId) toast.dismiss(toastId)
      inFlight.current.delete(label)
    }
  }

  function markReady(label) {
    showAfterUpdate.current.add(label)
    setNonces((prev) => ({ ...prev, [label]: String(Date.now()) }))
  }

  async function pollJob(jobId, serverId) {
    const start = Date.now()
    const url = `/api/authenticated/captions/jobs/${encodeURIComponent(jobId)}${
      serverId ? `?serverId=${encodeURIComponent(serverId)}` : ''
    }`
    while (Date.now() - start < POLL_TIMEOUT_MS) {
      await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS))
      try {
        const res = await fetch(url)
        if (!res.ok) continue
        const data = await res.json()
        if (data.status === 'succeeded' || data.status === 'failed') {
          return data
        }
      } catch (_) {
        // transient — keep polling
      }
    }
    return { status: 'failed', error: 'Polling timeout' }
  }

  if (!captions) return null

  return (
    <>
      {Object.entries(captions)
        .filter(([, c]) => c?.autoGenerated)
        .map(([label, c]) => {
          const nonce = nonces[label]
          const src = nonce
            ? `${c.url}${c.url.includes('?') ? '&' : '?'}_t=${nonce}`
            : c.url
          return (
            <Track
              key={`${label}-${nonce ?? 'init'}`}
              src={src}
              kind="subtitles"
              label={label}
              lang={c.srcLang}
            />
          )
        })}
    </>
  )
}

async function safeJson(res) {
  try {
    return await res.json()
  } catch {
    return null
  }
}
