'use client'

import { Track, useMediaPlayer } from '@vidstack/react'
import { useEffect, useRef, useState } from 'react'
import { useAutoCaptionsProgress } from './AutoCaptionsProgressContext'

const POLL_INTERVAL_MS = 3000
const POLL_TIMEOUT_MS = 15 * 60 * 1000

export default function AutoCaptionTracks({ captions }) {
  const player = useMediaPlayer()
  const { update: updateProgress, clear: clearProgress } = useAutoCaptionsProgress()

  // Nonce per label — appended to the Track src on success to force a fresh
  // fetch (the initial fetch returned 202; we need the browser to retry once
  // the file actually exists). The Track's React key stays stable so Vidstack
  // does NOT remount it — only the src prop updates.
  const [nonces, setNonces] = useState({})

  // In-flight: label is currently between trigger fetch and pollJob settling.
  // Processed: label has been processed once this video session — guards
  // against re-trigger when the user toggles the track off and back on, and
  // breaks the previous remount-loop on success.
  const inFlight = useRef(new Set())
  const processedLabels = useRef(new Set())

  useEffect(() => {
    if (!player?.textTracks) return
    const tt = player.textTracks

    // Vidstack's TextTrackList fires 'mode-change' (not the W3C 'change')
    // event. event.detail is the TextTrack that flipped mode.
    function onModeChange(event) {
      const track = event?.detail
      if (!track || track.mode !== 'showing') return
      const entry = captions?.[track.label]
      // Gate on autoGenerated only. The pending flag has been an unreliable
      // signal — the sync layer doesn't always preserve it. The trigger route
      // is idempotent (200 if file exists, 202 if generation needed) so
      // handleTrackSelected handles both cases via the status code.
      if (!entry?.autoGenerated) return
      if (inFlight.current.has(track.label)) return
      if (processedLabels.current.has(track.label)) return
      console.log(
        '[AutoCaptionTracks] track selected:',
        track.label,
        { autoGenerated: entry.autoGenerated, pending: entry.pending }
      )
      handleTrackSelected(track, entry)
    }

    console.log('[AutoCaptionTracks] subscribing to mode-change')
    tt.addEventListener('mode-change', onModeChange)
    return () => tt.removeEventListener('mode-change', onModeChange)
  }, [player, captions])

  // Re-assert mode='showing' after a successful generation. Confirmed in the
  // Vidstack source (@vidstack/react/dev/chunks/vidstack-DUlCophs.js): the
  // <Track> component recreates the TextTrack when any prop (including src)
  // changes — useMemo deps are Object.values(init). Effect cleanup calls
  // textTracks.remove(oldTrack), which explicitly sets `oldTrack.mode = "disabled"`
  // (line 1935). The new track is then added with default mode='disabled'.
  // useCaptionOptions.selected is computed live from `t.mode === "showing"`
  // (line 1905), so without re-asserting the selection, the menu snaps to "Off".
  //
  // We re-assert on TWO triggers to cover both possible orderings:
  //   1. The nonces state change itself (parent effect after child effects)
  //   2. The textTracks 'add' event (in case Vidstack's add lands after our
  //      effect runs — has been observed in practice)
  // The processedLabels guard in onModeChange prevents re-triggering the JIT
  // handler when our re-assert dispatches its own mode-change event.
  useEffect(() => {
    if (!player?.textTracks) return
    const tt = player.textTracks

    function reassertProcessed() {
      for (const label of Object.keys(nonces)) {
        if (!processedLabels.current.has(label)) continue
        const track = Array.from(tt).find((t) => t.label === label)
        if (track && track.mode !== 'showing') {
          console.log('[AutoCaptionTracks] re-asserting mode=showing for', label)
          track.mode = 'showing'
        }
      }
    }

    reassertProcessed()
    tt.addEventListener('add', reassertProcessed)
    return () => tt.removeEventListener('add', reassertProcessed)
  }, [nonces, player])

  async function handleTrackSelected(track, entry) {
    const label = track.label
    inFlight.current.add(label)

    // Surface "Generating…" on the row immediately so the user gets visual
    // confirmation on click — before the trigger fetch round-trips. For
    // already-ready tracks (200 path) the finally block clears it ~1 s later;
    // brief flicker is acceptable.
    updateProgress(label, { status: 'running', progressPct: null })

    try {
      const triggerRes = await fetch(entry.url)
      console.log('[AutoCaptionTracks] trigger response:', label, triggerRes.status)

      if (triggerRes.status === 200) {
        // File exists — the browser's automatic Track-load fetch also got 200
        // VTT, so cues are already populating. Mark processed; no nonce bump
        // needed since the existing src returned the right bytes.
        processedLabels.current.add(label)
        return
      }

      if (triggerRes.status !== 202) {
        // 401/429/503/etc. — silently dropped. Track stays as-is, user can retry.
        console.warn(`Auto-caption trigger returned HTTP ${triggerRes.status}`)
        return
      }

      const triggerBody = await safeJson(triggerRes)
      const jobId = triggerBody?.jobId
      if (!jobId) {
        console.warn('Auto-caption trigger accepted but no jobId returned')
        return
      }

      // Enrich the running state with the jobId now that we have it.
      updateProgress(label, { status: 'running', jobId, progressPct: null })
      console.log('[AutoCaptionTracks] polling job:', jobId, 'for', label)

      const result = await pollJob(jobId, entry.sourceServerId, (data) => {
        updateProgress(label, {
          status: data.status,
          progressPct: typeof data.progressPct === 'number' ? data.progressPct : null,
        })
      })

      if (result.status === 'succeeded') {
        // Mark processed BEFORE bumping the nonce so the resulting mode-change
        // events (if Vidstack fires any when it reloads cues) short-circuit
        // in the gate.
        processedLabels.current.add(label)
        // Bump the nonce → src prop changes → Vidstack updates the underlying
        // track's src → browser refetches the URL → now returns 200 VTT →
        // cues populate. Stable React key means the Track is NOT remounted,
        // so it stays in place in the menu.
        setNonces((prev) => ({ ...prev, [label]: String(Date.now()) }))
      } else {
        console.warn(`Auto-caption job failed: ${result.error || 'unknown error'}`)
      }
    } catch (err) {
      console.warn(`Auto-caption trigger error: ${err.message}`)
    } finally {
      inFlight.current.delete(label)
      // Drop the "Generating…" suffix on every code path — success leaves the
      // track loaded with cues; failures revert to the plain label.
      clearProgress(label)
    }
  }

  async function pollJob(jobId, serverId, onProgress) {
    const start = Date.now()
    const url = `/api/authenticated/captions/jobs/${encodeURIComponent(jobId)}${
      serverId ? `?serverId=${encodeURIComponent(serverId)}` : ''
    }`
    while (Date.now() - start < POLL_TIMEOUT_MS) {
      await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS))
      try {
        const res = await fetch(url)
        if (!res.ok) continue
        const data = await res.json()
        if (typeof onProgress === 'function') onProgress(data)
        if (data.status === 'succeeded' || data.status === 'failed') {
          return data
        }
      } catch (_) {
        // transient — keep polling
      }
    }
    return { status: 'failed', error: 'Polling timeout' }
  }

  if (!captions) return null

  return (
    <>
      {Object.entries(captions)
        .filter(([, c]) => c?.autoGenerated)
        .map(([label, c]) => {
          const nonce = nonces[label]
          const src = nonce
            ? `${c.url}${c.url.includes('?') ? '&' : '?'}_t=${nonce}`
            : c.url
          return (
            <Track
              // Stable key — only the src prop changes when we bump the nonce.
              // Vidstack updates the underlying TextTrack in place; no remount,
              // no re-add to the bottom of textTracks, no mode-change loop.
              key={label}
              src={src}
              kind="subtitles"
              label={label}
              lang={c.srcLang}
            />
          )
        })}
    </>
  )
}

async function safeJson(res) {
  try {
    return await res.json()
  } catch {
    return null
  }
}
