// Persistent caption-track preference.
//
// Stored as a structural fingerprint of the user's last selection rather than
// the literal track label so that the same intent ("I want English, not auto")
// can map to whichever variant happens to exist on the next video.
//
// Shape: { srcLang, preferAuto, hearingImpaired }

const STORAGE_KEY = 'mediaPlayerCaptionPreference'

export function loadPreference() {
  if (typeof window === 'undefined') return null
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY)
    if (!raw) return null
    const parsed = JSON.parse(raw)
    if (!parsed || typeof parsed.srcLang !== 'string') return null
    return {
      srcLang: parsed.srcLang,
      preferAuto: Boolean(parsed.preferAuto),
      hearingImpaired: Boolean(parsed.hearingImpaired),
    }
  } catch {
    return null
  }
}

export function savePreference(pref) {
  if (typeof window === 'undefined') return
  try {
    if (pref === null) {
      window.localStorage.removeItem(STORAGE_KEY)
    } else {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(pref))
    }
  } catch {
    // ignore quota / private mode errors
  }
}

export function isHearingImpairedLabel(label) {
  return /hearing\s+impaired/i.test(label || '')
}

/**
 * Pick the label of the track that best matches the user's stored preference.
 *
 * candidates: [{ label, srcLang, autoGenerated, hearingImpaired }]
 * pref: { srcLang, preferAuto, hearingImpaired } | null
 *
 * Rules (from product spec):
 *  - With pref: prefer exact match (srcLang + auto + HI). Otherwise fall back
 *    within the same srcLang preferring non-auto over auto.
 *  - Without pref: default to plain English (no auto, no HI). Fall back to any
 *    non-auto English. Don't auto-default to an auto-generated track — the user
 *    must opt in by clicking it.
 *  - Returns null when nothing matches; caller leaves captions off.
 */
export function pickPreferredLabel(candidates, pref) {
  if (!Array.isArray(candidates) || candidates.length === 0) return null

  if (pref) {
    const sameLang = candidates.filter((c) => c.srcLang === pref.srcLang)
    if (sameLang.length === 0) return null

    const exact = sameLang.find(
      (c) =>
        Boolean(c.autoGenerated) === Boolean(pref.preferAuto) &&
        Boolean(c.hearingImpaired) === Boolean(pref.hearingImpaired)
    )
    if (exact) return exact.label

    // Fallback within same lang — prefer non-auto regardless of HI mismatch
    const nonAuto = sameLang.find((c) => !c.autoGenerated)
    if (nonAuto) return nonAuto.label

    // Last resort: any same-lang track (likely auto)
    return sameLang[0].label
  }

  const englishTracks = candidates.filter((c) => c.srcLang === 'en')
  if (englishTracks.length === 0) return null

  const plain = englishTracks.find((c) => !c.autoGenerated && !c.hearingImpaired)
  if (plain) return plain.label

  const anyNonAuto = englishTracks.find((c) => !c.autoGenerated)
  if (anyNonAuto) return anyNonAuto.label

  // No non-auto English available — leave off; user opts in to auto explicitly.
  return null
}
