'use client'

import { useEffect, useRef } from 'react'
import { useMediaPlayer } from '@vidstack/react'
import {
  isHearingImpairedLabel,
  loadPreference,
  pickPreferredLabel,
  savePreference,
} from './captionPreference'

/**
 * Owns caption-track default selection + persistence per the user's stored
 * preference. Mounted inside <MediaProvider>.
 *
 * On video change:
 *   1. Wait until tracks have been added to player.textTracks (Vidstack adds
 *      them async after the JSX <Track> elements mount).
 *   2. Build a candidate list from textTracks ∩ captions metadata.
 *   3. Apply pickPreferredLabel(candidates, pref) → set that track to showing.
 *
 * On user-driven selection change:
 *   - Persist the new preference (debounced to collapse programmatic flips
 *     done by AutoCaptionTracks).
 *
 * `mediaKey` is whatever uniquely identifies the current video — used to
 * gate the initial-apply effect so navigating between videos re-applies the
 * preference exactly once per video.
 */
export default function CaptionPreferenceManager({ captions, mediaKey }) {
  const player = useMediaPlayer()
  const appliedForKeyRef = useRef(null)
  const lastShowingLabelRef = useRef(null)
  const persistTimerRef = useRef(null)

  // Apply preference once per video, retrying as tracks get added.
  useEffect(() => {
    if (!player?.textTracks || !captions) return
    const tt = player.textTracks
    appliedForKeyRef.current = null

    function buildCandidates() {
      const tracks = Array.from(tt)
      return tracks
        .map((t) => {
          const entry = captions[t.label]
          if (!entry) return null
          return {
            label: t.label,
            srcLang: t.language || entry.srcLang,
            autoGenerated: Boolean(entry.autoGenerated),
            hearingImpaired: isHearingImpairedLabel(t.label),
          }
        })
        .filter(Boolean)
    }

    function tryApply() {
      if (appliedForKeyRef.current === mediaKey) return
      const candidates = buildCandidates()
      if (candidates.length === 0) return // no caption tracks ready yet

      const pref = loadPreference()
      const preferredLabel = pickPreferredLabel(candidates, pref)
      if (preferredLabel) {
        const target = Array.from(tt).find((t) => t.label === preferredLabel)
        if (target && target.mode !== 'showing') {
          target.mode = 'showing'
          lastShowingLabelRef.current = preferredLabel
        } else if (target) {
          lastShowingLabelRef.current = preferredLabel
        }
      }
      appliedForKeyRef.current = mediaKey
    }

    tryApply()

    // Tracks may arrive after this effect runs — retry on each add.
    function onAdd() {
      tryApply()
    }
    tt.addEventListener('add', onAdd)
    return () => {
      tt.removeEventListener('add', onAdd)
    }
  }, [player, captions, mediaKey])

  // Persist user-driven selection changes. Debounced so transient flips
  // (AutoCaptionTracks disabling/re-enabling around generation) don't churn
  // the stored preference.
  useEffect(() => {
    if (!player?.textTracks || !captions) return
    const tt = player.textTracks

    // Vidstack's TextTrackList fires 'mode-change' (not 'change') when a
    // track's mode flips. Listening on the list so we hear about every track.
    function onModeChange() {
      if (persistTimerRef.current) clearTimeout(persistTimerRef.current)
      persistTimerRef.current = setTimeout(() => {
        const showing = Array.from(tt).find((t) => t.mode === 'showing')

        if (showing) {
          const entry = captions[showing.label]
          if (!entry) return
          savePreference({
            srcLang: showing.language || entry.srcLang,
            preferAuto: Boolean(entry.autoGenerated),
            hearingImpaired: isHearingImpairedLabel(showing.label),
          })
          lastShowingLabelRef.current = showing.label
          return
        }

        // No track showing. Treat as user-driven "Off" only if a track was
        // showing previously in this session — otherwise leave the existing
        // preference alone (probably a transient programmatic disable).
        if (lastShowingLabelRef.current) {
          savePreference(null)
          lastShowingLabelRef.current = null
        }
      }, 400)
    }

    tt.addEventListener('mode-change', onModeChange)
    return () => {
      tt.removeEventListener('mode-change', onModeChange)
      if (persistTimerRef.current) {
        clearTimeout(persistTimerRef.current)
        persistTimerRef.current = null
      }
    }
  }, [player, captions])

  return null
}
