'use client'

import { useEffect, useRef } from 'react'
import { useCaptionsOptions } from './videojs'
import {
  isHearingImpairedLabel,
  loadPreference,
  pickPreferredLabel,
  savePreference,
} from './captionPreference'

/**
 * Owns caption-track default selection + persistence per the user's stored
 * preference. Mounted inside the player provider.
 *
 * On video change:
 *   1. Wait until tracks surface in the captions menu options (the framework
 *      adds them async as the <track> elements load).
 *   2. Build a candidate list from options ∩ captions metadata.
 *   3. Apply pickPreferredLabel(candidates, pref) → select that option.
 *
 * On user-driven selection change:
 *   - Persist the new preference (debounced to collapse programmatic flips
 *     done by AutoCaptionsManager).
 *
 * `mediaKey` is whatever uniquely identifies the current video — used to
 * gate the initial-apply effect so navigating between videos re-applies the
 * preference exactly once per video. The stored preference itself is a single
 * GLOBAL localStorage key (see captionPreference.js).
 */
export default function CaptionPreferenceManager({ captions, mediaKey }) {
  const captionsOptions = useCaptionsOptions()
  const appliedForKeyRef = useRef(null)
  const lastShowingLabelRef = useRef(null)
  const persistTimerRef = useRef(null)
  // Suppress the persist listener while WE are applying the stored preference,
  // so a programmatic apply never re-saves (or overwrites) the preference.
  const applyingRef = useRef(false)

  // Apply preference once per video, retrying as tracks surface in options.
  useEffect(() => {
    if (!captionsOptions || !captions) return
    if (appliedForKeyRef.current === mediaKey) return

    const candidates = captionsOptions.options
      .filter((o) => o.value !== 'off')
      .map((o) => {
        const label = String(o.label)
        const entry = captions[label]
        if (!entry) return null
        return {
          label,
          value: o.value,
          srcLang: entry.srcLang,
          autoGenerated: Boolean(entry.autoGenerated),
          hearingImpaired: isHearingImpairedLabel(label),
        }
      })
      .filter(Boolean)

    if (candidates.length === 0) return // no caption tracks ready yet — retry on next options change

    const pref = loadPreference()
    const preferredLabel = pickPreferredLabel(candidates, pref)
    if (preferredLabel) {
      const target = candidates.find((c) => c.label === preferredLabel)
      if (target && captionsOptions.value !== target.value) {
        applyingRef.current = true
        captionsOptions.setValue(target.value)
      }
      lastShowingLabelRef.current = preferredLabel
    }
    appliedForKeyRef.current = mediaKey
  }, [captionsOptions, captions, mediaKey])

  // Reset the apply gate when the video changes.
  useEffect(() => {
    appliedForKeyRef.current = null
    lastShowingLabelRef.current = null
  }, [mediaKey])

  // Persist user-driven selection changes. Debounced so transient flips
  // (AutoCaptionsManager re-asserting around generation) don't churn the
  // stored preference.
  const selectedValue = captionsOptions?.value
  useEffect(() => {
    if (!captionsOptions || !captions) return
    if (selectedValue === undefined) return

    if (applyingRef.current) {
      applyingRef.current = false
      return
    }
    // Nothing applied yet — startup churn, not a user action.
    if (appliedForKeyRef.current === null) return

    if (persistTimerRef.current) clearTimeout(persistTimerRef.current)
    persistTimerRef.current = setTimeout(() => {
      if (selectedValue !== 'off') {
        const option = captionsOptions.options.find((o) => o.value === selectedValue)
        const label = option ? String(option.label) : null
        const entry = label ? captions[label] : null
        if (!entry) return
        savePreference({
          srcLang: entry.srcLang,
          preferAuto: Boolean(entry.autoGenerated),
          hearingImpaired: isHearingImpairedLabel(label),
        })
        lastShowingLabelRef.current = label
        return
      }

      // Selection is "Off". Treat as user-driven only if a track was showing
      // previously in this session — otherwise leave the existing preference
      // alone (probably a transient programmatic disable).
      if (lastShowingLabelRef.current) {
        savePreference(null)
        lastShowingLabelRef.current = null
      }
    }, 400)

    return () => {
      if (persistTimerRef.current) {
        clearTimeout(persistTimerRef.current)
        persistTimerRef.current = null
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedValue])

  return null
}
