'use client'

import { Video, HlsJsVideo } from './videojs'

/**
 * The media element for the main player: <HlsJsVideo> for JIT .m3u8 manifests
 * (hls.js-powered — full quality/audio menus in every browser, matching the
 * old forced-hls.js behavior), plain <Video> for direct files.
 *
 * All text tracks are native <track> children driven by React state:
 *  - chapters VTT → store.chaptersCues (chapter menu, seekbar ticks, titles)
 *  - sprite VTT (kind=metadata label=thumbnails) → Slider.Thumbnail previews
 *  - caption tracks; auto-generated ones first (menu order) with a nonce
 *    appended to the src after generation succeeds so the browser refetches.
 */
export default function PlayerMedia({
  videoURL,
  chaptersURL,
  thumbnailsURL,
  captions,
  nonces = {},
  onEnded,
}) {
  const isManifest = /\.m3u8($|\?)/i.test(videoURL || '')

  const trackEls = []
  if (chaptersURL) {
    trackEls.push(
      <track key="chapters" kind="chapters" src={chaptersURL} srcLang="en-US" default />
    )
  }
  if (thumbnailsURL) {
    trackEls.push(
      <track key="thumbnails" kind="metadata" label="thumbnails" src={thumbnailsURL} />
    )
  }
  if (captions) {
    const withNonce = (url, label) => {
      const nonce = nonces[label]
      if (!nonce) return url
      return `${url}${url.includes('?') ? '&' : '?'}_t=${nonce}`
    }
    // Auto-generated tracks mount FIRST so they appear before human captions
    // in track order. Default selection is applied by CaptionPreferenceManager.
    for (const [label, entry] of Object.entries(captions).filter(([, c]) => c?.autoGenerated)) {
      trackEls.push(
        <track
          key={`auto-${label}`}
          kind="subtitles"
          src={withNonce(entry.url, label)}
          label={label}
          srcLang={entry.srcLang}
        />
      )
    }
    for (const [label, entry] of Object.entries(captions).filter(([, c]) => !c?.autoGenerated)) {
      trackEls.push(
        <track
          key={`sub-${label}`}
          kind="subtitles"
          src={entry.url}
          label={label}
          srcLang={entry.srcLang}
        />
      )
    }
  }

  const commonProps = {
    autoPlay: true,
    playsInline: true,
    preload: 'auto',
    onEnded,
    className: 'h-full w-full',
  }

  return isManifest ? (
    <HlsJsVideo src={videoURL} streamType="on-demand" {...commonProps}>
      {trackEls}
    </HlsJsVideo>
  ) : (
    <Video src={videoURL} {...commonProps}>
      {trackEls}
    </Video>
  )
}
