'use client'

import { HlsJsVideo, NativeHlsVideo } from './videojs'

/** Whether a source is an HLS manifest rather than a progressive file. */
export function isManifestSource(url) {
  return /\.m3u8($|\?)/i.test(url || '')
}

const CONTAINER_MIME = {
  mp4: 'video/mp4',
  m4v: 'video/mp4',
  mov: 'video/mp4',
  webm: 'video/webm',
}

/**
 * MIME type for a source, for the Cast load request.
 *
 * The sender only infers a content type for HLS; a progressive file is sent
 * with an empty one, leaving the receiver to guess. Returns undefined for
 * anything unrecognised so the receiver keeps its own inference.
 */
export function castContentType(url) {
  if (isManifestSource(url)) return 'application/x-mpegURL'
  const ext = (url || '').split(/[?#]/)[0].split('.').pop()?.toLowerCase()
  return CONTAINER_MIME[ext]
}

/**
 * The media element for the main player: <HlsJsVideo> for JIT .m3u8 manifests
 * (hls.js-powered — full quality/audio menus in every browser, matching the
 * old forced-hls.js behavior), plain <Video> for direct files.
 *
 * All text tracks are native <track> children driven by React state:
 *  - chapters VTT → store.chaptersCues (chapter menu, seekbar ticks, titles)
 *  - sprite VTT (kind=metadata label=thumbnails) → Slider.Thumbnail previews
 *  - caption tracks; auto-generated ones first (menu order) with a nonce
 *    appended to the src after generation succeeds so the browser refetches.
 */
export default function PlayerMedia({
  videoURL,
  chaptersURL,
  thumbnailsURL,
  captions,
  nonces = {},
  onEnded,
  // Owned by MainVideoPlayer (teardown + visibility-pause + heartbeat gating).
  videoRef,
  // The receiver is already playing this title, so the local element must not
  // start alongside it — see MainVideoPlayer.
  suppressAutoplay = false,
}) {
  const isManifest = isManifestSource(videoURL)

  const trackEls = []
  if (chaptersURL) {
    trackEls.push(
      <track key="chapters" kind="chapters" src={chaptersURL} srcLang="en-US" default />
    )
  }
  if (thumbnailsURL) {
    // `default` puts the track in 'hidden' mode so the browser actually loads
    // the VTT — the store only reads cues, it never enables the track itself.
    // (Spec allows one default per kind category, so chapters+metadata is fine.)
    trackEls.push(
      <track key="thumbnails" kind="metadata" label="thumbnails" src={thumbnailsURL} default />
    )
  }
  if (captions) {
    const withNonce = (url, label) => {
      const nonce = nonces[label]
      if (!nonce) return url
      return `${url}${url.includes('?') ? '&' : '?'}_t=${nonce}`
    }
    // Auto-generated tracks mount FIRST so they appear before human captions
    // in track order. Default selection is applied by CaptionPreferenceManager.
    for (const [label, entry] of Object.entries(captions).filter(([, c]) => c?.autoGenerated)) {
      trackEls.push(
        <track
          key={`auto-${label}`}
          kind="subtitles"
          src={withNonce(entry.url, label)}
          label={label}
          srcLang={entry.srcLang}
        />
      )
    }
    for (const [label, entry] of Object.entries(captions).filter(([, c]) => !c?.autoGenerated)) {
      trackEls.push(
        <track
          key={`sub-${label}`}
          kind="subtitles"
          src={entry.url}
          label={label}
          srcLang={entry.srcLang}
        />
      )
    }
  }

  const commonProps = {
    autoPlay: !suppressAutoplay,
    playsInline: true,
    preload: 'auto',
    onEnded,
    className: 'h-screen min-h-screen w-full',
  }

  return isManifest ? (
    <HlsJsVideo ref={videoRef} src={videoURL} streamType="on-demand" {...commonProps}>
      {trackEls}
    </HlsJsVideo>
  ) : (
    // NativeHlsVideo, not a plain <Video>: for a non-manifest source it is just
    // `target.src = src` with no hls.js engine, but it IS a media host, which
    // is what lets <GoogleCast> register and cast to our own receiver.
    <NativeHlsVideo ref={videoRef} src={videoURL} streamType="on-demand" {...commonProps}>
      {trackEls}
    </NativeHlsVideo>
  )
}
