/**
 * dropStaleAutoCaptions: an auto-generated caption a server offered earlier
 * and no longer lists is removed from the stored captions. Nothing else is.
 */

import { dropStaleAutoCaptions } from '@src/utils/sync/core/staleAutoCaptions'

const AUTO = 'English - Auto Generated'

function auto(serverId, extra = {}) {
  return {
    srcLang: 'en',
    url: `https://${serverId}.example.com/api/captions/track/movie/A/en`,
    sourceServerId: serverId,
    autoGenerated: true,
    ...extra,
  }
}

function human(serverId) {
  return { srcLang: 'en', url: `https://${serverId}.example.com/movies/A/A.en.srt`, sourceServerId: serverId }
}

describe('dropStaleAutoCaptions', () => {
  it('removes a pending auto caption the server no longer lists', () => {
    const existing = { English: human('tower'), [AUTO]: auto('tower', { pending: true }) }
    const listed = { English: { url: '/movies/A/A.en.srt', srcLang: 'en' } }

    expect(dropStaleAutoCaptions(existing, listed, 'tower')).toEqual({
      captions: { English: existing.English },
      removed: [AUTO],
    })
  })

  it('removes a finished auto caption whose file was removed', () => {
    const existing = { [AUTO]: auto('tower') }

    expect(dropStaleAutoCaptions(existing, {}, 'tower')).toEqual({ captions: {}, removed: [AUTO] })
  })

  it('removes it when the server lists no captions at all', () => {
    const existing = { [AUTO]: auto('tower') }

    for (const listed of [null, undefined]) {
      expect(dropStaleAutoCaptions(existing, listed, 'tower')).toEqual({ captions: {}, removed: [AUTO] })
    }
  })

  it('keeps an auto caption the server still lists', () => {
    const existing = { [AUTO]: auto('tower', { pending: true }) }
    const listed = { [AUTO]: { url: 'https://tower.example.com/x', srcLang: 'en', autoGenerated: true, pending: true } }

    expect(dropStaleAutoCaptions(existing, listed, 'tower')).toEqual({ captions: existing, removed: [] })
  })

  it('never removes a caption a person supplied, listed or not', () => {
    const existing = { English: human('tower'), Spanish: human('tower') }

    expect(dropStaleAutoCaptions(existing, {}, 'tower')).toEqual({ captions: existing, removed: [] })
  })

  it("leaves another server's auto caption alone", () => {
    const existing = { [AUTO]: auto('attic') }

    expect(dropStaleAutoCaptions(existing, {}, 'tower')).toEqual({ captions: existing, removed: [] })
  })

  it('leaves an auto caption with no source stamp alone', () => {
    const existing = { [AUTO]: { srcLang: 'en', url: 'https://x', autoGenerated: true } }

    expect(dropStaleAutoCaptions(existing, {}, 'tower')).toEqual({ captions: existing, removed: [] })
  })

  it('matches by the caption key, per language', () => {
    const existing = {
      [AUTO]: auto('tower'),
      'Spanish - Auto Generated': auto('tower', { srcLang: 'es' }),
    }
    const listed = { [AUTO]: { url: 'https://tower.example.com/x' } }

    expect(dropStaleAutoCaptions(existing, listed, 'tower')).toEqual({
      captions: { [AUTO]: existing[AUTO] },
      removed: ['Spanish - Auto Generated'],
    })
  })

  it('does not mistake an inherited property name for a listed caption', () => {
    const existing = { toString: auto('tower'), constructor: auto('tower') }

    expect(dropStaleAutoCaptions(existing, {}, 'tower').removed).toEqual(['toString', 'constructor'])
  })

  it('has nothing to do for an entity with no stored captions', () => {
    for (const existing of [null, undefined, {}]) {
      expect(dropStaleAutoCaptions(existing, {}, 'tower')).toEqual({ captions: {}, removed: [] })
    }
  })

  it('does not change the stored object', () => {
    const existing = { [AUTO]: auto('tower') }
    dropStaleAutoCaptions(existing, {}, 'tower')

    expect(Object.keys(existing)).toEqual([AUTO])
  })
})
