'use client'

import { useState } from 'react'
import { TrashIcon, PlusIcon } from '@heroicons/react/24/outline'

/**
 * Editor for a movie/episode `captionURLs` object:
 *   { [label]: { srcLang, url } }
 *
 * Staged entirely in the parent's form state; `onChange` receives the rebuilt
 * captionURLs object on every add/remove.
 */
export default function CaptionsEditor({ captionURLs = {}, onChange }) {
  const [draft, setDraft] = useState({ label: '', srcLang: '', url: '' })
  const entries = Object.entries(captionURLs || {})

  function addCaption() {
    const label = draft.label.trim()
    const url = draft.url.trim()
    if (!label || !url) return
    onChange({
      ...captionURLs,
      [label]: { srcLang: draft.srcLang.trim() || label, url },
    })
    setDraft({ label: '', srcLang: '', url: '' })
  }

  function removeCaption(label) {
    const next = { ...captionURLs }
    delete next[label]
    onChange(next)
  }

  return (
    <div>
      <h3 className="text-sm font-medium text-gray-700">Captions</h3>
      {entries.length > 0 ? (
        <ul className="mt-2 divide-y divide-gray-100 rounded-md border border-gray-200">
          {entries.map(([label, details]) => (
            <li key={label} className="flex items-center gap-3 px-3 py-2 text-sm">
              <span className="w-24 shrink-0 font-medium text-gray-700">{label}</span>
              <span className="w-16 shrink-0 text-gray-500">{details?.srcLang}</span>
              <span className="flex-1 truncate text-gray-500" title={details?.url}>
                {details?.url}
              </span>
              {details?.autoGenerated && (
                <span className="rounded bg-sky-100 px-1.5 py-0.5 text-xs text-sky-700">auto</span>
              )}
              <button
                type="button"
                onClick={() => removeCaption(label)}
                className="text-gray-400 hover:text-red-600"
                title={`Remove ${label}`}
              >
                <TrashIcon className="h-4 w-4" />
              </button>
            </li>
          ))}
        </ul>
      ) : (
        <p className="mt-2 text-xs text-gray-400">No captions.</p>
      )}

      <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-[6rem_5rem_1fr_auto]">
        <input
          value={draft.label}
          onChange={(e) => setDraft((d) => ({ ...d, label: e.target.value }))}
          placeholder="Label (English)"
          className="rounded-md border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-900 placeholder:text-gray-400"
        />
        <input
          value={draft.srcLang}
          onChange={(e) => setDraft((d) => ({ ...d, srcLang: e.target.value }))}
          placeholder="srcLang (en)"
          className="rounded-md border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-900 placeholder:text-gray-400"
        />
        <input
          value={draft.url}
          onChange={(e) => setDraft((d) => ({ ...d, url: e.target.value }))}
          placeholder="https://…/subtitles.vtt"
          className="rounded-md border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-900 placeholder:text-gray-400"
        />
        <button
          type="button"
          onClick={addCaption}
          className="inline-flex items-center justify-center gap-1 rounded-md bg-gray-800 px-2 py-1.5 text-sm font-medium text-white hover:bg-gray-700"
        >
          <PlusIcon className="h-4 w-4" /> Add
        </button>
      </div>
    </div>
  )
}
