/**
 * One server's pass over a title's `captionURLs`.
 *
 * A caption language belongs to the highest-priority server that lists it.
 * The pass used to REPLACE the stored map with the languages the syncing
 * server owns, and to do nothing at all when that server listed none. So:
 *
 *  - two servers with different languages overwrote each other on every run
 *    (English after one pass, Spanish after the next);
 *  - a removed subtitle stayed for good once it was the last one, because an
 *    empty list never replaced anything.
 *
 * The pass now edits the stored map entry by entry, and the result does not
 * depend on the order the servers are synced in:
 *
 *  1. A language this server lists AND owns is written with this server's
 *     entry.
 *  2. An entry this server wrote earlier, for a language it no longer lists,
 *     is removed. The server that supplied it says it is gone; no other
 *     server's answer is needed for that.
 *  3. An entry for a language NO server lists is removed, but only on a run in
 *     which every enabled server answered — a server that is down has not
 *     withdrawn its subtitles.
 *
 * Everything else is left as it is: another server's entry for a language it
 * still owns, and any entry whose owner is unknown while a server is missing.
 * An entry kept only for that last reason is reported as `withheld`: the caller
 * must not mark its pass complete, or the removal would never be retried.
 *
 * The map is returned in a fixed order (English first, then by name) whenever
 * it changes. It used to keep the order entries happened to be added in, which
 * depended on server order and on the title's history, and the player lists
 * tracks in stored order.
 *
 * Pure: returns the next map and whether it differs. Never writes.
 */

export interface CaptionEntry {
  url?: string
  srcLang?: string
  lastModified?: string
  sourceServerId?: string
  autoGenerated?: boolean
  pending?: boolean
}

export interface CaptionReconcileInput<T extends CaptionEntry> {
  /** The entity's stored `captionURLs`. */
  existing: Record<string, T> | null | undefined
  /** What the syncing server lists now, already converted to stored form. */
  listed: Record<string, T> | null | undefined
  /** The server being synced. */
  serverId: string
  /** Whether the syncing server is the highest-priority server listing a language. */
  ownsLanguage: (language: string) => boolean
  /** Whether any server lists a language this run. */
  listedByAnyServer: (language: string) => boolean
  /** True only when every enabled server answered this run. */
  allEnabledServersProbed: boolean
}

export interface CaptionReconcileResult<T extends CaptionEntry> {
  captions: Record<string, T>
  changed: boolean
  /** Languages written or replaced by this pass. */
  written: string[]
  /** Languages removed by this pass. */
  removed: string[]
  /**
   * Languages no server lists that were kept because not every server answered
   * this run. They are due for removal on a run where every server does.
   */
  withheld: string[]
}

// MongoDB stores a field set to `undefined` as `null`, so a value that was
// never there reads back as null. The two are the same thing here; comparing
// them strictly made every auto-caption stub (which has no lastModified) look
// changed on every pass.
const same = (a: unknown, b: unknown) => (a ?? null) === (b ?? null)

function sameEntry(a: CaptionEntry | undefined, b: CaptionEntry | undefined): boolean {
  if (!a || !b) return false
  return (
    same(a.url, b.url) &&
    same(a.srcLang, b.srcLang) &&
    same(a.lastModified, b.lastModified) &&
    same(a.sourceServerId, b.sourceServerId) &&
    Boolean(a.autoGenerated) === Boolean(b.autoGenerated) &&
    Boolean(a.pending) === Boolean(b.pending)
  )
}

/** English first, then by name: the order the track menu shows them in. */
function inDisplayOrder<T>(captions: Record<string, T>): Record<string, T> {
  const isEnglish = (name: string) => name.toLowerCase().includes('english')
  const names = Object.keys(captions).sort((a, b) => {
    if (isEnglish(a) !== isEnglish(b)) return isEnglish(a) ? -1 : 1
    return a < b ? -1 : a > b ? 1 : 0
  })
  return Object.fromEntries(names.map((name) => [name, captions[name]]))
}

export function reconcileCaptions<T extends CaptionEntry>(
  input: CaptionReconcileInput<T>
): CaptionReconcileResult<T> {
  const existing = input.existing && typeof input.existing === 'object' ? input.existing : {}
  const listed = input.listed && typeof input.listed === 'object' ? input.listed : {}
  const captions: Record<string, T> = { ...existing }
  const written: string[] = []
  const removed: string[] = []
  const withheld: string[] = []

  for (const [language, entry] of Object.entries(listed)) {
    if (!input.ownsLanguage(language)) continue
    if (!sameEntry(captions[language], entry)) {
      captions[language] = entry
      written.push(language)
    }
  }

  for (const [language, entry] of Object.entries(existing)) {
    if (Object.prototype.hasOwnProperty.call(listed, language)) continue
    const withdrawnByItsServer = entry?.sourceServerId === input.serverId
    const listedNowhere = !input.listedByAnyServer(language)
    if (withdrawnByItsServer || (listedNowhere && input.allEnabledServersProbed)) {
      delete captions[language]
      removed.push(language)
    } else if (listedNowhere) {
      withheld.push(language)
    }
  }

  const changed = written.length > 0 || removed.length > 0
  return {
    captions: changed ? inDisplayOrder(captions) : captions,
    changed,
    written,
    removed,
    withheld,
  }
}
