/**
 * Auto-generated captions a server offered earlier and no longer does.
 *
 * A file server lists an auto-generated caption for a title (a "pending" stub
 * the player can ask it to make, or the finished `.auto.srt`) only while it can
 * make or serve one. It stops when the title turns out to have no audio in the
 * caption's language, or when a caption made from the wrong audio is removed.
 *
 * The caption sync only ever added and overwrote entries, so such an entry
 * stayed in `captionURLs` for good and the player went on offering a caption
 * the server refuses to make. This drops exactly those: entries marked
 * `autoGenerated`, stamped with the syncing server's id, that the server's
 * current list no longer has. Another server's entries, and every caption a
 * person supplied, are left alone.
 */

interface CaptionEntry {
  autoGenerated?: boolean
  sourceServerId?: string
}

/**
 * @param existing - The entity's stored `captionURLs`
 * @param listed - What the server lists for it now, keyed the same way (the
 *   payload's `subtitles`); null or undefined when it lists none
 * @param serverId - The server being synced
 * @returns The stored captions without the stale ones, and the keys removed
 */
export function dropStaleAutoCaptions<T extends CaptionEntry>(
  existing: Record<string, T> | null | undefined,
  listed: Record<string, unknown> | null | undefined,
  serverId: string
): { captions: Record<string, T>; removed: string[] } {
  const captions: Record<string, T> = {}
  const removed: string[] = []
  const stillListed = listed && typeof listed === 'object' ? listed : {}

  for (const [key, entry] of Object.entries(existing || {})) {
    const stale =
      entry?.autoGenerated === true &&
      entry.sourceServerId === serverId &&
      !Object.prototype.hasOwnProperty.call(stillListed, key)
    if (stale) {
      removed.push(key)
    } else {
      captions[key] = entry
    }
  }

  return { captions, removed }
}
