/**
 * Pure helpers behind the movie / episode info pages: the colon-split title,
 * the quality chips on the meta line, and the technical facts panel. No React
 * and no I/O so every rule here is unit tested against real document shapes.
 *
 * Inputs are the flat documents as `getFlatRequestedMedia` returns them:
 * `dimensions` ("3840x2160"), `size` (bytes), `hdr` ("HDR10" / "Dolby Vision"),
 * `mediaQuality` (format, bitDepth, viewingExperience), `sources[]`
 * (container, videoCodec, pixFmt, audioTrackCount, audioLanguages),
 * `captionURLs` (keyed by label, `pending`/`autoGenerated` flags),
 * `mediaLastModified` (file mtime) and `videoSource` (server id).
 */

/**
 * Split "The Hobbit: An Unexpected Journey" into a headline and a subtitle.
 * Only a colon followed by whitespace splits; a colon inside a word ("Mission:
 * Impossible" still splits — that is the franchise convention) and trailing
 * colons do not.
 *
 * @param {string|null|undefined} title
 * @returns {{ headline: string, subtitle: string|null }}
 */
export function splitTitle(title) {
  const text = typeof title === 'string' ? title.trim() : ''
  const at = text.indexOf(': ')
  if (at <= 0) return { headline: text, subtitle: null }
  const headline = text.slice(0, at).trim()
  const subtitle = text.slice(at + 2).trim()
  if (!headline || !subtitle) return { headline: text, subtitle: null }
  return { headline, subtitle }
}

/**
 * Four-digit year from a date-ish value, or null.
 *
 * @param {string|Date|null|undefined} value
 * @returns {string|null}
 */
export function yearOf(value) {
  if (!value) return null
  const d = value instanceof Date ? value : new Date(value)
  return Number.isNaN(d.getTime()) ? null : String(d.getUTCFullYear())
}

/**
 * "3840x2160" → { width, height } or null.
 */
export function parseDimensions(dimensions) {
  if (typeof dimensions !== 'string') return null
  const m = dimensions.match(/^\s*(\d+)\s*[x×]\s*(\d+)\s*$/i)
  if (!m) return null
  return { width: Number(m[1]), height: Number(m[2]) }
}

/**
 * The short label a viewer recognises: 4K, 1080p, 720p, SD.
 *
 * Either side can earn the label, so a 1920x800 scope film reads 1080p by
 * its width and a 1440x1080 4:3 transfer reads 1080p by its height.
 *
 * @param {string|null|undefined} dimensions
 * @returns {string|null}
 */
export function resolutionLabel(dimensions) {
  const dims = parseDimensions(dimensions)
  if (!dims) return null
  const { width, height } = dims
  if (width >= 3800 || height >= 2100) return '4K'
  if (width >= 1900 || height >= 1000) return '1080p'
  if (width >= 1260 || height >= 700) return '720p'
  return 'SD'
}

const CODEC_NAMES = {
  hevc: 'HEVC (H.265)',
  h265: 'HEVC (H.265)',
  h264: 'H.264',
  avc: 'H.264',
  av1: 'AV1',
  vp9: 'VP9',
  mpeg4: 'MPEG-4',
  mpeg2video: 'MPEG-2',
  vc1: 'VC-1',
}

/**
 * ffprobe codec id → the name people know.
 */
export function codecName(codec) {
  if (typeof codec !== 'string' || !codec) return null
  const key = codec.toLowerCase()
  return CODEC_NAMES[key] || codec.toUpperCase()
}

/**
 * Bit depth from a pixel format ("yuv420p10le" → 10, "yuv420p" → 8).
 */
export function bitDepthFromPixFmt(pixFmt) {
  if (typeof pixFmt !== 'string') return null
  const m = pixFmt.match(/p(\d{2})(?:le|be)?$/)
  return m ? Number(m[1]) : pixFmt.startsWith('yuv') || pixFmt.startsWith('rgb') ? 8 : null
}

/**
 * Bytes → "7.07 GB" (1024-based, the way media managers report file sizes).
 *
 * @param {number|string|{ toString(): string }|null|undefined} bytes
 * @returns {string|null}
 */
export function formatBytes(bytes) {
  const n = typeof bytes === 'number' ? bytes : Number(bytes?.toString?.() ?? bytes)
  if (!Number.isFinite(n) || n <= 0) return null
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  let value = n
  let i = 0
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024
    i += 1
  }
  const digits = i >= 3 ? 2 : i === 2 ? 1 : 0
  return `${value.toFixed(digits)} ${units[i]}`
}

const LANGUAGE_FALLBACK = {
  en: 'English',
  eng: 'English',
  es: 'Spanish',
  spa: 'Spanish',
  fr: 'French',
  fra: 'French',
  fre: 'French',
  de: 'German',
  deu: 'German',
  ger: 'German',
  it: 'Italian',
  ita: 'Italian',
  ja: 'Japanese',
  jpn: 'Japanese',
  ko: 'Korean',
  kor: 'Korean',
  zh: 'Chinese',
  zho: 'Chinese',
  chi: 'Chinese',
  pt: 'Portuguese',
  por: 'Portuguese',
  ru: 'Russian',
  rus: 'Russian',
  hi: 'Hindi',
  hin: 'Hindi',
  tl: 'Tagalog',
  tgl: 'Tagalog',
  und: 'Unknown',
}

let displayNames = null
function languageDisplayNames() {
  if (displayNames !== null) return displayNames
  try {
    displayNames = typeof Intl !== 'undefined' && Intl.DisplayNames ? new Intl.DisplayNames(['en'], { type: 'language' }) : false
  } catch {
    displayNames = false
  }
  return displayNames
}

/**
 * ISO 639-1 / 639-2 code → English name. Unknown codes come back as-is,
 * upper-cased, rather than vanishing.
 *
 * @param {string|null|undefined} code
 * @returns {string|null}
 */
export function languageName(code) {
  if (typeof code !== 'string' || !code.trim()) return null
  const key = code.trim().toLowerCase()
  if (LANGUAGE_FALLBACK[key]) return LANGUAGE_FALLBACK[key]
  const names = /^[a-z]{2,3}$/.test(key) ? languageDisplayNames() : null
  if (names) {
    try {
      const name = names.of(key)
      if (name && name.toLowerCase() !== key) return name
    } catch {
      // RangeError for a malformed tag — fall through to the raw code
    }
  }
  return code.toUpperCase()
}

/**
 * Distinct language names, in first-seen order, from a list of codes.
 */
export function languageNames(codes) {
  if (!Array.isArray(codes)) return []
  const seen = new Set()
  const out = []
  for (const code of codes) {
    const name = languageName(code)
    if (name && !seen.has(name)) {
      seen.add(name)
      out.push(name)
    }
  }
  return out
}

/**
 * The primary file's probe data, whichever shape the document carries.
 */
export function primarySource(media) {
  const sources = Array.isArray(media?.sources) ? media.sources : []
  return sources.find((s) => s?.isPrimary) || sources[0] || null
}

/**
 * The chips on the meta line: resolution, then dynamic-range formats. Reads
 * the document's own `hdr` label first, then the probe flags, so "Dolby
 * Vision" beats a generic "HDR" and nothing is listed twice.
 *
 * @param {Object} media
 * @returns {string[]}
 */
export function qualityChips(media) {
  const chips = []
  const res = resolutionLabel(media?.dimensions || primarySource(media)?.dimensions)
  if (res && res !== 'SD') chips.push(res)

  const seen = new Set()
  const add = (label) => {
    if (label && !seen.has(label)) {
      seen.add(label)
      chips.push(label)
    }
  }

  const declared = typeof media?.hdr === 'string' ? media.hdr.trim() : ''
  if (declared) {
    // "Dolby Vision, HDR10" style values carry more than one format
    // (a "+" stays put: it is part of "HDR10+")
    declared
      .split(/\s*[,/&]\s*|\s+and\s+/i)
      .map((s) => s.trim())
      .filter(Boolean)
      .forEach(add)
  }

  const ve = media?.mediaQuality?.viewingExperience
  if (ve?.dolbyVision) add('Dolby Vision')
  if (ve?.hdr10Plus) add('HDR10+')
  if (ve?.standardHDR && !seen.has('HDR10') && !seen.has('HDR10+') && !seen.has('Dolby Vision')) add('HDR')

  return chips
}

/**
 * Certification the way the catalog stores it ("PG-13", "TV-MA"), or null
 * for the placeholder values TMDB sometimes leaves behind.
 */
export function certificationOf(metadata) {
  const raw = metadata?.rating
  if (typeof raw !== 'string') return null
  const value = raw.trim()
  if (!value || value.toUpperCase() === 'NR' || value.toUpperCase() === 'N/A') return null
  return value
}

/**
 * Subtitle languages available now, and the ones still being generated.
 *
 * @param {Object|null|undefined} captionURLs - keyed by label
 * @returns {{ ready: string[], pending: string[] }}
 */
export function subtitleSummary(captionURLs) {
  const ready = []
  const pending = []
  if (!captionURLs || typeof captionURLs !== 'object') return { ready, pending }
  for (const [label, entry] of Object.entries(captionURLs)) {
    if (!entry || typeof entry !== 'object') continue
    const base = label.replace(/\s*-\s*auto generated$/i, '').trim()
    const name = entry.autoGenerated ? `${base} (auto)` : base
    if (entry.pending) {
      pending.push(base)
    } else if (!ready.includes(name)) {
      ready.push(name)
    }
  }
  return { ready, pending }
}

/**
 * Names of the people with a given set of jobs, in credit order, de-duplicated.
 */
export function crewNames(crew, jobs) {
  if (!Array.isArray(crew)) return []
  const wanted = new Set(jobs.map((j) => j.toLowerCase()))
  const seen = new Set()
  const out = []
  for (const person of crew) {
    const job = typeof person?.job === 'string' ? person.job.toLowerCase() : ''
    if (!wanted.has(job) || !person?.name || seen.has(person.name)) continue
    seen.add(person.name)
    out.push(person.name)
  }
  return out
}

const WRITER_JOBS = ['Writer', 'Screenplay', 'Story', 'Teleplay', 'Novel', 'Author', 'Original Story', 'Characters']

/**
 * Human date, or null.
 */
export function formatDate(value, options = { year: 'numeric', month: 'short', day: 'numeric' }) {
  if (!value) return null
  const d = value instanceof Date ? value : new Date(value)
  if (Number.isNaN(d.getTime())) return null
  return new Intl.DateTimeFormat('en-US', { timeZone: 'UTC', ...options }).format(d)
}

/**
 * The technical rows shared by both pages. Every row is `{ label, value }`
 * with a string value (or an array of strings for a chip list); rows with
 * nothing to say are left out rather than shown as "Unknown".
 *
 * @param {Object} media
 * @param {{ sourceHost?: string|null }} [extras]
 * @returns {Array<{ label: string, value: string|string[], note?: string }>}
 */
export function fileFacts(media, extras = {}) {
  const rows = []
  const source = primarySource(media)
  const dims = parseDimensions(media?.dimensions || source?.dimensions)

  if (dims) {
    const label = resolutionLabel(media?.dimensions || source?.dimensions)
    rows.push({ label: 'Resolution', value: `${dims.width} × ${dims.height}${label ? ` (${label})` : ''}` })
  }

  const codec = codecName(source?.videoCodec)
  const depth = media?.mediaQuality?.bitDepth ?? bitDepthFromPixFmt(source?.pixFmt)
  if (codec || depth) {
    rows.push({ label: 'Video', value: [codec, depth ? `${depth}-bit` : null].filter(Boolean).join(' · ') })
  }

  const range = media?.mediaQuality?.format || (typeof media?.hdr === 'string' && media.hdr) || null
  if (range) rows.push({ label: 'Dynamic range', value: range })

  const audioLangs = languageNames(source?.audioLanguages)
  const trackCount = Number.isFinite(source?.audioTrackCount) ? source.audioTrackCount : null
  if (audioLangs.length || trackCount) {
    const count = trackCount ? `${trackCount} track${trackCount === 1 ? '' : 's'}` : null
    rows.push({ label: 'Audio', value: [count, audioLangs.join(', ') || null].filter(Boolean).join(' · ') })
  }

  const subs = subtitleSummary(media?.captionURLs)
  if (subs.ready.length || subs.pending.length) {
    rows.push({
      label: 'Subtitles',
      value: subs.ready.length ? subs.ready.join(', ') : 'None yet',
      note: subs.pending.length ? `${subs.pending.join(', ')} auto-captions generating` : undefined,
    })
  }

  const container = (media?.primaryContainer || source?.container || '').toString().toUpperCase() || null
  const size = formatBytes(media?.size ?? source?.size)
  if (container || size) rows.push({ label: 'File', value: [container, size].filter(Boolean).join(' · ') })

  const added = formatDate(media?.mediaLastModified || media?.initialDiscoveryDate || media?.createdAt)
  if (added) rows.push({ label: 'Added', value: added })

  if (extras.sourceHost) rows.push({ label: 'Source', value: extras.sourceHost })

  return rows
}

/**
 * Rows for a movie: the catalog facts the hero does not already show (the
 * year, runtime, certification and quality chips live on the meta line),
 * then the file facts. Studios stand in for a director/writer credit
 * because the movie documents carry TMDB cast but no crew.
 */
export function movieFacts(media, extras = {}) {
  const rows = []
  const meta = media?.metadata || {}

  const original = languageName(meta.original_language)
  if (original) rows.push({ label: 'Language', value: original })

  const spoken = languageNames((meta.spoken_languages || []).map((l) => l?.iso_639_1).filter(Boolean))
    .filter((name) => name !== original)
  if (spoken.length) rows.push({ label: 'Also spoken', value: spoken.join(', ') })

  const studios = (meta.production_companies || []).map((c) => c?.name).filter(Boolean)
  if (studios.length) rows.push({ label: 'Studio', value: studios.slice(0, 3).join(', ') })

  const countries = (meta.production_countries || []).map((c) => c?.name).filter(Boolean)
  if (countries.length) rows.push({ label: 'Country', value: countries.slice(0, 3).join(', ') })

  const released = formatDate(meta.release_date)
  if (released) rows.push({ label: 'Released', value: released })

  const vote = Number(meta.vote_average)
  if (Number.isFinite(vote) && vote > 0) rows.push({ label: 'TMDB score', value: `${vote.toFixed(1)} / 10` })

  return rows.concat(fileFacts(media, extras))
}

/**
 * Rows for an episode: the episode's own credits first, then the show facts
 * and the file facts. The air date, runtime and certification are on the
 * meta line, so they are not repeated here.
 */
export function episodeFacts(media, extras = {}) {
  const rows = []
  const meta = media?.metadata || {}

  const directors = crewNames(meta.crew, ['Director'])
  if (directors.length) rows.push({ label: directors.length > 1 ? 'Directors' : 'Director', value: directors.join(', ') })

  const writers = crewNames(meta.crew, WRITER_JOBS)
  if (writers.length) rows.push({ label: writers.length > 1 ? 'Writers' : 'Writer', value: writers.slice(0, 4).join(', ') })

  const networks = (meta.networks || []).map((n) => n?.name).filter(Boolean)
  if (networks.length) rows.push({ label: 'Network', value: networks.join(', ') })

  const original = languageName(meta.original_language)
  if (original) rows.push({ label: 'Language', value: original })

  const vote = Number(meta.vote_average)
  if (Number.isFinite(vote) && vote > 0) rows.push({ label: 'TMDB score', value: `${vote.toFixed(1)} / 10` })

  return rows.concat(fileFacts(media, extras))
}

/**
 * "Season finale" / "Mid-season finale" for the meta line, or null.
 */
export function episodeTypeLabel(episodeType) {
  switch (episodeType) {
    case 'finale':
      return 'Season finale'
    case 'mid_season':
      return 'Mid-season finale'
    default:
      return null
  }
}

/**
 * Host name of the file server that owns a title's video, for the panel.
 * Takes the resolved server config so this stays pure.
 */
export function sourceHostOf(serverConfig) {
  const base = serverConfig?.baseURL
  if (typeof base !== 'string' || !base) return null
  try {
    return new URL(base).hostname
  } catch {
    return null
  }
}
