/**
 * The info page's pure helpers, run against the shapes the flat documents
 * actually carry (a 1080p SDR animated film and a 4K HDR10 episode, copied
 * from production with the long fields trimmed).
 */

const {
  splitTitle,
  yearOf,
  resolutionLabel,
  codecName,
  bitDepthFromPixFmt,
  formatBytes,
  languageName,
  languageNames,
  qualityChips,
  certificationOf,
  subtitleSummary,
  crewNames,
  movieFacts,
  episodeFacts,
  episodeTypeLabel,
  sourceHostOf,
} = require('@src/utils/media/detailsFacts')

const hobbit = {
  title: 'The Hobbit',
  hdr: null,
  dimensions: '1440x1080',
  size: 7593365532,
  duration: 4645120,
  primaryContainer: 'mp4',
  videoSource: 'default',
  mediaLastModified: '2025-04-22T21:41:23.822Z',
  initialDiscoveryDate: '2026-07-09T13:42:45.987Z',
  mediaQuality: {
    format: '8-bit SDR (BT.709)',
    bitDepth: 8,
    isHDR: false,
    viewingExperience: { enhancedColor: false, highDynamicRange: false, dolbyVision: false, hdr10Plus: false, standardHDR: false },
  },
  captionURLs: {
    English: { srcLang: 'en', url: 'https://x/en.srt' },
    Spanish: { srcLang: 'es', url: 'https://x/es.srt' },
    'English - Auto Generated': { srcLang: 'en', url: 'https://x/auto', autoGenerated: true, pending: true },
  },
  sources: [
    {
      container: 'mp4',
      videoCodec: 'h264',
      pixFmt: 'yuv420p',
      hdr: null,
      audioTrackCount: 1,
      audioLanguages: ['eng'],
      size: 7593365532,
      dimensions: '1440x1080',
      isPrimary: true,
    },
  ],
  metadata: {
    rating: 'PG',
    original_language: 'en',
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
    production_companies: [{ name: 'Rankin/Bass Productions' }, { name: 'Topcraft' }],
    production_countries: [{ iso_3166_1: 'JP', name: 'Japan' }, { iso_3166_1: 'US', name: 'United States of America' }],
    release_date: '1977-11-27T00:00:00.000Z',
    vote_average: 6.6,
    runtime: 77,
  },
}

const countdown = {
  title: 'Countdown',
  showTitle: '3 Body Problem',
  seasonNumber: 1,
  episodeNumber: 1,
  hdr: 'HDR10',
  dimensions: '3840x2160',
  size: { toString: () => '5366482273' },
  duration: 3635199,
  primaryContainer: 'mp4',
  mediaLastModified: '2025-08-11T03:29:22.482Z',
  mediaQuality: {
    format: 'HDR10',
    bitDepth: 10,
    isHDR: true,
    viewingExperience: { enhancedColor: true, highDynamicRange: true, dolbyVision: false, hdr10Plus: false, standardHDR: true },
  },
  captionURLs: {
    'English Hearing Impaired': { srcLang: 'en', url: 'https://x/en.hi.srt' },
    Spanish: { srcLang: 'es', url: 'https://x/es.srt' },
    Tagalog: { srcLang: 'tl', url: 'https://x/tl.srt' },
    'English - Auto Generated': { srcLang: 'en', url: 'https://x/auto', autoGenerated: true, pending: true },
  },
  sources: [
    { container: 'mp4', videoCodec: 'hevc', pixFmt: 'yuv420p10le', hdr: 'HDR10', audioTrackCount: 2, audioLanguages: ['eng'], size: 5366482273 },
  ],
  metadata: {
    air_date: '2024-03-21',
    episode_type: 'standard',
    runtime: 61,
    vote_average: 7.411,
    rating: 'TV-MA',
    networks: [{ name: 'Netflix' }],
    original_language: 'en',
    crew: [
      { job: 'Director', department: 'Directing', name: 'Derek Tsang Kwok-Cheung' },
      { job: 'Writer', department: 'Writing', name: 'David Benioff' },
      { job: 'Writer', department: 'Writing', name: 'D. B. Weiss' },
      { job: 'Writer', department: 'Writing', name: 'Alexander Woo' },
      { job: 'Editor', department: 'Editing', name: 'Katie Weiland' },
      { job: 'Director of Photography', department: 'Camera', name: 'Jonathan Freeman' },
    ],
  },
}

describe('splitTitle', () => {
  it('splits a franchise title on the first colon-space', () => {
    expect(splitTitle('The Hobbit: An Unexpected Journey')).toEqual({ headline: 'The Hobbit', subtitle: 'An Unexpected Journey' })
    expect(splitTitle('Mission: Impossible - Fallout')).toEqual({ headline: 'Mission', subtitle: 'Impossible - Fallout' })
  })

  it('leaves plain titles, trailing colons and odd spacing alone', () => {
    expect(splitTitle('The Hobbit')).toEqual({ headline: 'The Hobbit', subtitle: null })
    expect(splitTitle('Hobbit:')).toEqual({ headline: 'Hobbit:', subtitle: null })
    expect(splitTitle('12:01')).toEqual({ headline: '12:01', subtitle: null })
    expect(splitTitle(': Nothing')).toEqual({ headline: ': Nothing', subtitle: null })
    expect(splitTitle(null)).toEqual({ headline: '', subtitle: null })
  })
})

describe('small formatters', () => {
  it('reads the year from a date string or Date', () => {
    expect(yearOf('1977-11-27T00:00:00.000Z')).toBe('1977')
    expect(yearOf(new Date('2024-03-21'))).toBe('2024')
    expect(yearOf('nope')).toBeNull()
    expect(yearOf(null)).toBeNull()
  })

  it('labels resolutions on the long side', () => {
    expect(resolutionLabel('3840x2160')).toBe('4K')
    expect(resolutionLabel('1920x800')).toBe('1080p')
    expect(resolutionLabel('1440x1080')).toBe('1080p')
    expect(resolutionLabel('1280x720')).toBe('720p')
    expect(resolutionLabel('720x576')).toBe('SD')
    expect(resolutionLabel('garbage')).toBeNull()
  })

  it('names codecs and reads bit depth from the pixel format', () => {
    expect(codecName('hevc')).toBe('HEVC (H.265)')
    expect(codecName('h264')).toBe('H.264')
    expect(codecName('vp8')).toBe('VP8')
    expect(codecName(null)).toBeNull()
    expect(bitDepthFromPixFmt('yuv420p10le')).toBe(10)
    expect(bitDepthFromPixFmt('yuv420p')).toBe(8)
    expect(bitDepthFromPixFmt(undefined)).toBeNull()
  })

  it('formats file sizes the way media managers do', () => {
    expect(formatBytes(7593365532)).toBe('7.07 GB')
    expect(formatBytes({ toString: () => '5366482273' })).toBe('5.00 GB')
    expect(formatBytes(734003200)).toBe('700.0 MB')
    expect(formatBytes(0)).toBeNull()
    expect(formatBytes('abc')).toBeNull()
  })

  it('turns language codes into names and keeps unknown ones visible', () => {
    expect(languageName('en')).toBe('English')
    expect(languageName('eng')).toBe('English')
    expect(languageName('tl')).toBe('Tagalog')
    expect(languageName('xx-zz-unknown')).toBe('XX-ZZ-UNKNOWN')
    expect(languageNames(['eng', 'en', 'spa'])).toEqual(['English', 'Spanish'])
    expect(languageNames(null)).toEqual([])
  })
})

describe('qualityChips', () => {
  it('shows resolution and dynamic range once each, in that order', () => {
    expect(qualityChips(hobbit)).toEqual(['1080p'])
    expect(qualityChips(countdown)).toEqual(['4K', 'HDR10'])
  })

  it('reads a combined hdr label and the probe flags without repeating', () => {
    expect(qualityChips({ dimensions: '3840x2160', hdr: 'Dolby Vision, HDR10', mediaQuality: { viewingExperience: { dolbyVision: true, standardHDR: true } } })).toEqual([
      '4K',
      'Dolby Vision',
      'HDR10',
    ])
    expect(qualityChips({ dimensions: '3840x2160', mediaQuality: { viewingExperience: { standardHDR: true } } })).toEqual(['4K', 'HDR'])
    expect(qualityChips({ dimensions: '3840x2160', hdr: 'HDR10+' })).toEqual(['4K', 'HDR10+'])
    expect(qualityChips({})).toEqual([])
  })
})

describe('certification and subtitles', () => {
  it('drops placeholder ratings', () => {
    expect(certificationOf({ rating: 'PG-13' })).toBe('PG-13')
    expect(certificationOf({ rating: 'NR' })).toBeNull()
    expect(certificationOf({ rating: '' })).toBeNull()
    expect(certificationOf(null)).toBeNull()
  })

  it('separates ready tracks from auto-captions still generating', () => {
    expect(subtitleSummary(hobbit.captionURLs)).toEqual({ ready: ['English', 'Spanish'], pending: ['English'] })
    expect(subtitleSummary({ 'English - Auto Generated': { autoGenerated: true, pending: false } })).toEqual({
      ready: ['English (auto)'],
      pending: [],
    })
    expect(subtitleSummary(null)).toEqual({ ready: [], pending: [] })
  })
})

describe('crewNames', () => {
  it('picks the jobs asked for, in credit order, without repeats', () => {
    expect(crewNames(countdown.metadata.crew, ['Director'])).toEqual(['Derek Tsang Kwok-Cheung'])
    expect(crewNames(countdown.metadata.crew, ['Writer', 'Screenplay'])).toEqual(['David Benioff', 'D. B. Weiss', 'Alexander Woo'])
    expect(crewNames(undefined, ['Director'])).toEqual([])
  })
})

describe('movieFacts', () => {
  it('lists what the hero does not already show, then the file facts', () => {
    const rows = movieFacts(hobbit, { sourceHost: 'personalserver.adamdrumm.com' })
    expect(rows.map((r) => r.label)).toEqual([
      'Language',
      'Studio',
      'Country',
      'Released',
      'TMDB score',
      'Resolution',
      'Video',
      'Dynamic range',
      'Audio',
      'Subtitles',
      'File',
      'Added',
      'Source',
    ])
    const byLabel = Object.fromEntries(rows.map((r) => [r.label, r]))
    expect(byLabel.Language.value).toBe('English')
    expect(byLabel.Studio.value).toBe('Rankin/Bass Productions, Topcraft')
    expect(byLabel.Released.value).toBe('Nov 27, 1977')
    expect(byLabel['TMDB score'].value).toBe('6.6 / 10')
    expect(byLabel.Resolution.value).toBe('1440 × 1080 (1080p)')
    expect(byLabel.Video.value).toBe('H.264 · 8-bit')
    expect(byLabel['Dynamic range'].value).toBe('8-bit SDR (BT.709)')
    expect(byLabel.Audio.value).toBe('1 track · English')
    expect(byLabel.Subtitles).toEqual({ label: 'Subtitles', value: 'English, Spanish', note: 'English auto-captions generating' })
    expect(byLabel.File.value).toBe('MP4 · 7.07 GB')
    expect(byLabel.Added.value).toBe('Apr 22, 2025')
    expect(byLabel.Source.value).toBe('personalserver.adamdrumm.com')
  })

  it('leaves out rows with nothing to say instead of printing Unknown', () => {
    const rows = movieFacts({ metadata: {} })
    expect(rows).toEqual([])
  })
})

describe('episodeFacts', () => {
  it('leads with the episode credits and the show facts', () => {
    const rows = episodeFacts(countdown)
    const byLabel = Object.fromEntries(rows.map((r) => [r.label, r]))
    expect(rows.slice(0, 5).map((r) => r.label)).toEqual(['Director', 'Writers', 'Network', 'Language', 'TMDB score'])
    expect(byLabel.Director.value).toBe('Derek Tsang Kwok-Cheung')
    expect(byLabel.Writers.value).toBe('David Benioff, D. B. Weiss, Alexander Woo')
    expect(byLabel.Network.value).toBe('Netflix')
    expect(byLabel.Resolution.value).toBe('3840 × 2160 (4K)')
    expect(byLabel.Video.value).toBe('HEVC (H.265) · 10-bit')
    expect(byLabel['Dynamic range'].value).toBe('HDR10')
    expect(byLabel.Audio.value).toBe('2 tracks · English')
    expect(byLabel.Subtitles.value).toBe('English Hearing Impaired, Spanish, Tagalog')
    expect(byLabel.File.value).toBe('MP4 · 5.00 GB')
  })

  it('names finales for the meta line', () => {
    expect(episodeTypeLabel('finale')).toBe('Season finale')
    expect(episodeTypeLabel('mid_season')).toBe('Mid-season finale')
    expect(episodeTypeLabel('standard')).toBeNull()
  })
})

describe('sourceHostOf', () => {
  it('reads the host out of a server config, tolerating junk', () => {
    expect(sourceHostOf({ baseURL: 'https://personalserver.adamdrumm.com/media' })).toBe('personalserver.adamdrumm.com')
    expect(sourceHostOf({ baseURL: 'not a url' })).toBeNull()
    expect(sourceHostOf(null)).toBeNull()
  })
})
